[git]
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->â›°ï¸  Features" },
  { message = "^fix", group = "<!-- 1 -->ğŸ› Bug Fixes" },
  { message = "^refactor", group = "<!-- 2 -->ğŸšœ Refactor" },
  { message = "^doc", group = "<!-- 3 -->ğŸ“š Documentation" },
  { message = "^perf", group = "<!-- 4 -->ğŸš€ Performance" },
  { message = "^refactor\\(clippy\\)", skip = true },
  { message = "^style", group = "<!-- 5 -->ğŸ¨ Styling" },
  { message = "^test", group = "<!-- 6 -->ğŸ§ª Testing" },
  { message = "^chore: beta release", skip = true },
  { message = "^chore: Release", skip = true },
  { message = "^chore: Update changelog", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = "^chore\\(npm\\).*yarn\\.lock", skip = true },
  { message = "^ci", group = "<!-- 7 -->ğŸ“¦ CI/CD" },
  { message = "^chore", group = "<!-- 8 -->âš™ï¸ Miscellaneous Tasks" },
  { body = ".*security", group = "<!-- 9 -->ğŸ›¡ï¸ Security" },
  { message = "^revert", group = "<!-- 10 -->ğŸ”™ Revert" },
]
